export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_USER_LOCATION = 'UPDATE_USER_LOCATION';
export const ADD_NEW_LOCATION = 'ADD_NEW_LOCATION';
export const GET_ALL_PLACES = 'GET_ALL_PLACES';
export const LOGOUT = 'LOGOUT';
//
export const CHANGE_USER_PHONE = 'CHANGE_USER_PHONE';
export const CHANGE_INTERNET_CONNECTION = 'CHANGE_INTERNET_CONNECTION';
export const CHANGE_ALERT_MODAL = 'CHANGE_ALERT_MODAL';
export const CHANGE_LOADER_MODAL = 'CHANGE_LOADER_MODAL';
//
export const DELETE_ADDRESS = 'DELETE_ADDRESS';
export const CHANGE_TO_PRIME_LOC = 'CHANGE_TO_PRIME_LOC';
export const LOAD_PLACE_DELETE = 'LOAD_PLACE_DELETE';
export const MODIFY_LOCATION = 'MODIFY_LOCATION';
//

export const INC_CART = 'INC_CART';
export const DEC_CART = 'DEC_CART';
export const INIT_CART = 'INIT_CART';
